# Font
font_family JetBrains Mono
font_size 12

# Colors
background #000000 
foreground #ffffff

# Cursor
cursor #f5e0dc
cursor_shape block

# Window
background_opacity 0.10
window_padding_width 10

# Scrollback
scrollback_lines 10000
